/** Tailwind classes for the demo screen. The kit's components carry their own themes. */
export const theme = {
  screen: "flex-1 bg-white dark:bg-zinc-950",
  header: "flex-row items-center justify-between border-b border-zinc-100 bg-white px-4 pb-3 dark:border-zinc-900 dark:bg-zinc-950",
  headerLeft: "flex-row items-center gap-3",
  headerTitle: "text-[16px] font-semibold text-zinc-900 dark:text-zinc-50",
  headerSubtitleRow: "flex-row items-center gap-1.5",
  onlineDot: "h-1.5 w-1.5 rounded-full bg-emerald-500",
  headerSubtitle: "text-xs text-zinc-500 dark:text-zinc-400",
  newChatButton: "flex-row items-center gap-1.5 rounded-full border border-zinc-200 px-3 py-1.5 active:bg-zinc-100 dark:border-zinc-800 dark:active:bg-zinc-900",
  newChatLabel: "text-[13px] font-medium text-zinc-700 dark:text-zinc-300",
  newChatIcon: "bg-zinc-700 dark:bg-zinc-300",
  avatar: "h-8 w-8 items-center justify-center rounded-full bg-zinc-900 dark:bg-zinc-100",
  avatarSmall: "mt-0.5 h-7 w-7 items-center justify-center rounded-full bg-zinc-900 dark:bg-zinc-100",
  avatarGlyph: "text-[13px] text-white dark:text-zinc-900",
  list: "flex-1",
  listContent: "py-3",
  empty: "flex-1 items-center justify-center px-8",
  emptyLogo: "mb-5 h-14 w-14 items-center justify-center rounded-2xl bg-zinc-900 dark:bg-zinc-100",
  emptyLogoGlyph: "text-2xl text-white dark:text-zinc-900",
  emptyTitle: "text-center text-2xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-50",
  emptySubtitle: "mt-2 text-center text-[15px] leading-[22px] text-zinc-500 dark:text-zinc-400",
  suggestions: "pb-2",
  status: "mb-1 text-xs text-zinc-500 dark:text-zinc-400",
  statusError: "mb-1 text-xs text-rose-600 dark:text-rose-400",
} as const;
